language: python
os: linux
dist: xenial
python:
  - '3.6'
  - '3.8'
  - '3.9'
env:
  global:
    - OMP_NUM_THREADS=4
    # pypi-test key
    - secure: "VX8LK+nuJ8HbBsmsr8CtKCGMDLV6DZgVNL6aC+HHh7gm7nC0BJO/1QejOq4Rep25LebrZxRhsAvOJLPS0wgObAsFGorOhZHWA0W8khwvjvZqvu3eRDGdS9gTyPTlgxvig9cZ/D964rLHvP2qnKdFwjYOEbfZhfxvkbGk6uSe6kMRUoggG5ZsglYYpbUu75lz9o+KlDlv80fqVKo/XtKx4rngvgNWLVGWK08nJ/RtlHTLjcaR0/txtcQ7TpDLiYEwUohyKil42RbqU1+vvBo4olOyPWY7k2KYXWA2uv/cCY7eJjF0gQhq4M9be7pa2/s2I2YmnKY3RcAFWkItBqrNdCboF0FMC/LlTtYBdxAfx9D2b+0Syue3A2FekA+LV58+QtftEVuyCcJ1IFIQxEZp2lyGA2YoZEgS/FUsYfGR7nWyj1uzeyvK654odILFzuwy6axmaKaPTbiq2sgmJrAUjM4nCl50hu75U4L9vRXFJupkU7fPOsi/jbZsCrxyYSSFucXRu3JgO+DIWJRemCzqLyxQFWVcXf7WMaxHTpbulLxjLe2ALvOrTM/fOossxrISQTbMZYDUoeBNclHx3Z9T3+Vpth9M4RSul6IkosvDtndu4KrjSjoY93OxAYj3GaRoOTnghxxxXu55ZI1D+BUrELMPhZoC1AIcGOhnrQowg5w="
install:
  - pip3 install --upgrade pip
  - pip3 install setuptools wheel
  - pip3 install numpy scipy pyqt5 matplotlib pytest
  - python3 setup.py install
script:
  - pytest -v test/SimpleSchrodinger.py
  - python3 test/SimpleSchrodinger.py MP
  - pytest -v test/testMaterial.py
  - pytest -v test/testQuantumWell.py
  - pytest -v test/testThreeBandMatrix.py
  - pytest -v test/testEffMass.py
  - pytest -v test/testQCLayers.py
  - pytest -v test/testMaxwell.py
jobs:
  include:
  - stage: test
    name: MacOS default without MP
    os: osx
    osx_image: xcode11.5
    language: shell       # 'language: python' is an error on Travis CI macOS
    script:
      - python3 test/SimpleSchrodinger.py
      - pytest -v test/testQCLayers.py
  - name: MacOS with GCC
    os: osx
    osx_image: xcode11.5
    language: shell       # 'language: python' is an error on Travis CI macOS
    before_install:
      - brew install llvm
    env:
      - CC=gcc-10 OMP_NUM_THREADS=4
  - name: MacOS with Clang
    os: osx
    osx_image: xcode11.5
    language: shell       # 'language: python' is an error on Travis CI macOS
    before_install:
      - brew install llvm
    env:
      - CC=/usr/local/opt/llvm/bin/clang OMP_NUM_THREADS=4
  - name: Windows
    os: windows
    language: cpp
    env:
      - PATH=/c/Python38:/c/Python38/Scripts:$PATH MSBUILD_PATH="/C/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin" OMP_NUM_THREADS=4
    install:
      - choco install python --version 3.8.0
      - python -m pip install --upgrade pip
      - pip3 install setuptools wheel
      - pip3 install numpy scipy pyqt5 matplotlib pytest
      - export PATH=$MSBUILD_PATH:$PATH
      - export MSBUILD=msbuild.exe
      - python setup.py install
      - ls ErwinJr2/OneDQuantum
    script:
      - python test/SimpleSchrodinger.py
      - python test/SimpleSchrodinger.py MP
      - pytest -v test/testQuantumWell.py
      - pytest -v test/testQCLayers.py
  - stage: deploy
    name: Deploy Source
    env:
      - PYEXE=python3
    install:
      - pip3 install setuptools wheel twine
    script:
      - bash .travis/deploy.sh sdist
      # https://github.com/travis-ci/dpl/issues/1009
      # not using default pypi deploy because its bug on Win and Mac
  - name: Deploy Windows with VS
    os: windows
    language: cpp
    env:
      - PATH=/c/Python38:/c/Python38/Scripts:$PATH MSBUILD_PATH="/C/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin" PYEXE=python
    install:
      - choco install python --version 3.8.0
      - python -m pip install --upgrade pip
      - pip3 install setuptools wheel twine
      - export PATH=$MSBUILD_PATH:$PATH
      - export MSBUILD=msbuild.exe
    script:
      - bash .travis/deploy.sh bdist_wheel
  - name: Deploy MacOS with Clang
    os: osx
    osx_image: xcode11.5
    language: shell
    before_install:
      - brew install llvm
      - pip3 install setuptools wheel twine
    env:
      - CC=/usr/local/opt/llvm/bin/clang PYEXE=python3
    script:
      - bash .travis/deploy.sh bdist_wheel
