language: python
python:
    - "3.6"
sudo: false
env:
    - OMP_NUM_THREADS=4
install:
    - pip install -r requirements.txt
    - python install.py
script:
    - python -m unittest -v test/SimpleSchrodinger.py
    - python -m unittest -v test/SimpleSchrodinger.py MP
    - python -m unittest -v test/testMaterial.py
