language: python
python:
  - '3.8'
  - '3.7'
  - '3.6'
sudo: false
addons:
    apt:
        packages:
            - doxygen
            - doxygen-doc 
            - doxygen-latex
            - doxygen-gui
            - graphviz
env:
    - OMP_NUM_THREADS=4 
install:
    - pip3 install numpy scipy matplotlib sphinx sphinx_rtd_theme sphinxcontrib-bibtex breathe pytest
    - python3 install.py --docs --noshortcut
script:
    - pytest -v test/SimpleSchrodinger.py
    - python3 test/SimpleSchrodinger.py MP
    - pytest -v test/testMaterial.py
    - pytest -v test/testQCLayers.py
jobs:
  include:
  # other OSs are only tested for compiling and MP
  - name: MacOS with GCC
    os: osx
    osx_image: xcode11.5
    language: shell       # 'language: python' is an error on Travis CI macOS
    before_install:
      - brew install doxygen llvm
    env: 
      - CC=gcc-9 OMP_NUM_THREADS=4 
    script:
      - python3 test/SimpleSchrodinger.py MP

