language: python
os: linux
dist: xenial
python:
  - '3.6'
  - '3.8'
  - '3.9'
env:
  global:
    - OMP_NUM_THREADS=4
    # pypi-test key
    - secure: "KU0YVPMBF5Usce11OKQ3sp4SC/wYOUVcLjDxZCGwLdwmri/5e5UGbl4ENHvuwIr5TdneA+DJ859vHNKPlmuW1ApbarXpbdxd4c5Rlv7ZK1aI6Vb5NbcQtq4XgE4orO1nJHea3DP+V546+vQkgOomdWYSQ72lTtKPBaMYyqajhUUdM6HW1mVY29GaarRP9ls89uSlNyUHwvHPushhQ2JNoeD+rIhh/00cPRdyIEkO/gGJ7UF4XIUnnyzhrV1UPO7Ob1SaHcnEelyVXfIkOU23f2czf66wO2UD2xWyDKkDi6ricSNX4tODsJ6hHdw+0lcG7rZK1xUTOUgNscnWu48SMpesNl7dZLCLdkJpO+1jYJeJLua/3GOOSbAt54QWfr32aLvXbERU8kHxGlQch2c380DX38GTH5hVhciqCRCvRFn2iDzJL6smccDTJLVEaX1cuOflzGaBVyHnAVROFnTmeiioQczwc4S2zv0+ihECuepcnZNWbpYFtaDUAtAobPSwvguce/SzOkO6ODs/65CmYmxJ9jmOf0mkqOeQGsfeaol+SjRJw95hDGqPELIDSAeAkZhRhzJmNx0z3wCqMbSDk5KoJBKjtfgKlydOZNf5w4Nd/23SXzESd/YAi7FrVjC4EAbwL2e6qhgavRwuxn3Dw3Mser3/deT8QOpn/BsMKjg="
    # pypi key
    - secure: "mRXeTpg6iOJcZCSY5xK1orIeWkyTrM01QH5+IdzVhcUhsPcND/GquBcKxxJ83MkhuI05oYYDXcqGwZCVh/oVNrC+9KenNLCXR0rGaouKBjeXqbLPF1iaPkAPypMPiCx+7gCyeEHqhsdmAlt4lSFvROiMDr4yGfa/orp/cXXm5c0bGz8j3pxVwf8zEiVg2y6xzEBKi88iQV6yartwT15lRTNPHyeAt0MlRaF6roEUAWtp13sCXk1cyCUl/k3BUZu+eEydmT+n1T7hJSeEugB5QEeWs3HM/lT6iwAtuZi6M/H5YqCzP5Mk1ICwpT8EIQLsf/mbsXue62qPcjamYfaz0b5M5si9Z2bcBxkU42RQMFmzPY1D7p2/hMU+LVdTUpflVKr9hPlQrGJivYYSNBQFvkti8KdWdY6ZryQv8UUk/CHH4u4baaBz8eBB++Swfufq+f4mgJFLnxxsBbxFD8pf1z4HWeuRA5pfbaRpOba1P9SkxIvn8BkaMcGJAryVS2+om6CIJ/pPOVaTVM5bH/gin7iD9hlqP30ParRojR1GTaGff56Y9BND4JycsEmRI1veKGyWITptScDr25axU27aGDNI+sGcSPphJijASSMfcZKB2RdP94uni5VRRWEzLbAhDLf5PtWuv5r28/pGlPsgOeCW1jijQeLlyBv827OYZgk="
install:
  - pip3 install --upgrade pip
  - pip3 install setuptools wheel
  - pip3 install numpy scipy pyqt5 matplotlib pytest
  - python3 setup.py install
script:
  - pytest -v test/SimpleSchrodinger.py
  - python3 test/SimpleSchrodinger.py MP
  - pytest -v test/testMaterial.py
  - pytest -v test/testQuantumWell.py
  - pytest -v test/testThreeBandMatrix.py
  - pytest -v test/testEffMass.py
  - pytest -v test/testQCLayers.py
  - pytest -v test/testMaxwell.py
jobs:
  include:
  - stage: test
    name: MacOS default without MP
    os: osx
    osx_image: xcode11.5
    language: shell       # 'language: python' is an error on Travis CI macOS
    script:
      - python3 test/SimpleSchrodinger.py
      - pytest -v test/testQCLayers.py
  - name: MacOS with GCC
    os: osx
    osx_image: xcode11.5
    language: shell       # 'language: python' is an error on Travis CI macOS
    addons:
      homebrew:
        packages:
          - llvm
          - gcc@10
        update: true
    env:
      - CC=gcc-10 OMP_NUM_THREADS=4
  - name: MacOS with Clang
    os: osx
    osx_image: xcode11.5
    language: shell       # 'language: python' is an error on Travis CI macOS
    addons:
      homebrew:
        packages:
          - llvm
        update: true
    env:
      - CC=/usr/local/opt/llvm/bin/clang OMP_NUM_THREADS=4
  - name: Windows
    os: windows
    language: cpp
    env:
      - PATH=/c/Python38:/c/Python38/Scripts:$PATH MSBUILD_PATH="/C/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin" OMP_NUM_THREADS=4
    install:
      - choco install python --version 3.8.0
      - python -m pip install --upgrade pip
      - pip3 install setuptools wheel
      - pip3 install numpy scipy pyqt5 matplotlib pytest
      - export PATH=$MSBUILD_PATH:$PATH
      - export MSBUILD=msbuild.exe
      - python setup.py install
      - ls ErwinJr2/OneDQuantum
    script:
      - python test/SimpleSchrodinger.py
      - python test/SimpleSchrodinger.py MP
      - pytest -v test/testQuantumWell.py
      - pytest -v test/testQCLayers.py
  - stage: deploy
    name: Deploy Source
    env:
      - PYEXE=python3
    install:
      - pip3 install setuptools wheel twine
    script:
      - bash .travis/deploy.sh sdist
      # https://github.com/travis-ci/dpl/issues/1009
      # not using default pypi deploy because its bug on Win and Mac
  - name: Deploy Windows with VS
    os: windows
    language: cpp
    env:
      - PATH=/c/Python38:/c/Python38/Scripts:$PATH MSBUILD_PATH="/C/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin" PYEXE=python
    install:
      - choco install python --version 3.8.0
      - python -m pip install --upgrade pip
      - pip3 install setuptools wheel twine
      - export PATH=$MSBUILD_PATH:$PATH
      - export MSBUILD=msbuild.exe
    script:
      - bash .travis/deploy.sh bdist_wheel
  - name: Deploy MacOS with Clang
    os: osx
    osx_image: xcode11.5
    language: shell
    addons:
      homebrew:
        packages:
          - llvm
        update: true
    before_install:
      - pip3 install setuptools wheel twine
    env:
      - CC=/usr/local/opt/llvm/bin/clang PYEXE=python3
    script:
      - bash .travis/deploy.sh bdist_wheel
