language: python
os: linux
dist: xenial
python:
  - '3.6'
  - '3.8'
  - '3.9'
env:
  global:
    - OMP_NUM_THREADS=4
    # pypi-test key
    - secure: "vxZP/4ivCyzmxbjiFR28yIlibmfk4fNGEpX58f8+IYOH7533uwoGaE4I7hUHO4XNjgeaBwwPWyi8KccCts8XxEZPBVD17wBnHIvDH7KkDu/OFUVufVZgSsWYeIwZFqP8sj0eB8u8HfJjCk0zgjUdg71iupQf7tZlKbHTp9DGiFEI6UnniTlMvQ8xr2vcWKRR4unraFrTjLKf+8sLWZf9JPeEWTBhQaxSV9u0R3fp/E+Bo4Aei2e8oZALpVDMIGWNQYQ9mQAtpGK/OAVEcOGMV9zWvzYpKKCIaMcpTbB5TTF2vW7miS55ESfDZCg0VHYKr/jsIDDPddU+Ld3ZFDAXXQvLNk8TNVLNBxeX1lzTm93nOnYNDXIMCniB0/PhtCM2eY/c9C3FWCdbkARVFHZei6Gi5WpfXEc67NYyH+hLydojDLLVAvL5BrxjboEdnYUXd4fETCRs+iiRjhYFuOnNym3Uhexrbk51rbNnNgkeUZkEOrwQDknjCyF/n8oaO9+AFpm79qCDiOFXZmXWWFtQ6nelRd8E3RmzsZSeXYPgEggwWnoyIkAdEeVpgQTC1O+14ZJ4ck9KN+9SXdvYbF1pqPHGXmOQkbU8XRHZLONfeuxGa83jGyEwk0Cm5Ubqt4bCl8n208r2dS4q674Sc0HIcQvHggG7HIRLJ6EMrjCoTto="
    # pypi key
    - secure: "4k1TYEft5R/kyoFCecDHDgIfibHCUpy2A5MK0P52ELBoow5X3HTFiywxZ66QJn6hdd4Jq86cLYEQCPT6WKyXYUfbCmU7tkyDIEgnq45r2Njw1vS8ACtmwIIpz2xPzNX3giZwhXXFlDnLOLuhWunvmAvVlk181ncuKQyqHi4A2lpWDpxA7EVHGZK2Nf4i9XrKlnLXeTV/mtO872xp64fBmSrIj8l1J5Q/QAT4QsBjSdNmN+MBojpVxxhJu5fER48bdUevJGzmJ9aIn8zVmUr4SddeV+7dYJYOQJ+jYcB+W83Ph/byU+M72bAhFrz8fLSy3l7/PG/DriDpKEz7WMGwuN1p3M7CoeFhMiK4aiscKLl1qZC3ur53LN7wJnoVaDz/GwifPpuLk1u1NBq+NeoQwnQCT6c3gyoKloET+POHfl7zLyedb9rbuQv87JZPw38nrhHQ6gQY5uCzdPVrxAHWGMyQFFms5F3V+pzcH6ZHzSTYMh7xRvKwbDWaZVec1YvlgLukCs25S8v/j6lXvJVwDs4185aJBZXJcuDzD85GtckQ4Yw+aWqY5Fi4K93xGUeEqIewaHcKk6gSTSneYEOZm/PZaCEVCk8fLWxc7uVsZqzpOjvhNWxSxWLvLutaNpJJnABAQ8xjFZljhh1oZD+mhfxGhT2/oI3u/n8WKi/239g="
install:
  - pip3 install --upgrade pip
  - pip3 install setuptools wheel
  - pip3 install numpy scipy pyqt5 matplotlib pytest
  - python3 setup.py install
script:
  - pytest -v test/SimpleSchrodinger.py
  - python3 test/SimpleSchrodinger.py MP
  - pytest -v test/testMaterial.py
  - pytest -v test/testQuantumWell.py
  - pytest -v test/testThreeBandMatrix.py
  - pytest -v test/testEffMass.py
  - pytest -v test/testQCLayers.py
  - pytest -v test/testMaxwell.py
jobs:
  include:
  - stage: test
    name: MacOS default without MP
    os: osx
    osx_image: xcode11.5
    language: shell       # 'language: python' is an error on Travis CI macOS
    script:
      - python3 test/SimpleSchrodinger.py
      - pytest -v test/testQCLayers.py
  - name: MacOS with GCC
    os: osx
    osx_image: xcode11.5
    language: shell       # 'language: python' is an error on Travis CI macOS
    addons:
      homebrew:
        packages:
          - llvm
          - gcc@10
        update: true
    env:
      - CC=gcc-10 OMP_NUM_THREADS=4
  - name: MacOS with Clang
    os: osx
    osx_image: xcode11.5
    language: shell       # 'language: python' is an error on Travis CI macOS
    addons:
      homebrew:
        packages:
          - llvm
        update: true
    env:
      - CC=/usr/local/opt/llvm/bin/clang OMP_NUM_THREADS=4
  - name: Windows
    os: windows
    language: cpp
    env:
      - PATH=/c/Python38:/c/Python38/Scripts:$PATH MSBUILD_PATH="/C/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin" OMP_NUM_THREADS=4
    install:
      - choco install python --version 3.8.0
      - python -m pip install --upgrade pip
      - pip3 install setuptools wheel
      - pip3 install numpy scipy pyqt5 matplotlib pytest
      - export PATH=$MSBUILD_PATH:$PATH
      - export MSBUILD=msbuild.exe
      - python setup.py install
      - ls ErwinJr2/OneDQuantum
    script:
      - python test/SimpleSchrodinger.py
      - python test/SimpleSchrodinger.py MP
      - pytest -v test/testQuantumWell.py
      - pytest -v test/testQCLayers.py
  - stage: deploy
    name: Deploy Source
    env:
      - PYEXE=python3
    install:
      - pip3 install setuptools wheel twine
    script:
      - bash .travis/deploy.sh sdist
      # https://github.com/travis-ci/dpl/issues/1009
      # not using default pypi deploy because its bug on Win and Mac
  - name: Deploy Windows with VS
    os: windows
    language: cpp
    env:
      - PATH=/c/Python38:/c/Python38/Scripts:$PATH MSBUILD_PATH="/C/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin" PYEXE=python
    install:
      - choco install python --version 3.8.0
      - python -m pip install --upgrade pip
      - pip3 install setuptools wheel twine
      - export PATH=$MSBUILD_PATH:$PATH
      - export MSBUILD=msbuild.exe
    script:
      - bash .travis/deploy.sh bdist_wheel
  - name: Deploy MacOS with Clang
    os: osx
    osx_image: xcode11.5
    language: shell
    addons:
      homebrew:
        packages:
          - llvm
        update: true
    before_install:
      - pip3 install setuptools wheel twine
    env:
      - CC=/usr/local/opt/llvm/bin/clang PYEXE=python3
    script:
      - bash .travis/deploy.sh bdist_wheel
